# Generated by Django 4.1.4 on 2023-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
