name: performance-test-bench
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *" # Run every 3 days at 7:15 PM UTC

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ${{ github.workspace }}/tests/test.js
