name: performance-test-bench
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *" # Run every 3 days at 7:15 PM UTC
  push:
    branches:
      - perf_test

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ${{ github.workspace }}/tests/test.js
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Test image
        uses: docker/build-push-action@v5
        with:
          context: tests
          file: tests/Dockerfile
          tags: tests:latest
          outputs: type=docker,dst=/tmp/tests.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build performance Test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: performances/Dockerfile
          tags: perf-tests:latest
          outputs: type=docker,dst=/tmp/perf-tests.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
